spring:
  application:
    name: review-producer
  cloud:
    stream:
      bindings:
        reviewSupplier-out-0:
          destination: ${kafkaprops.reviewPlacedTopic}
          producer:
            use-native-encoding: true
            partition-key-expression: headers['X-PARTITION-KEY']
            partition-count: 3
      kafka:
        binder:
          brokers: localhost:9092
          replication-factor: 1
        bindings:
          reviewSupplier-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                schema.registry.url: http://localhost:8081


kafkaprops:
  reviewPlacedTopic: review.placement.v1
  partitionCount: 3
server:
  port: 9000